#!/bin/bash
#
# Copyright (c) 2024, The beep-projects contributors
# this file originated from https://github.com/beep-projects
# Do not remove the lines above.
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/
#
# This file is inspired by the firstrun.sh, generated by the Raspberry Pi Imager https://www.raspberrypi.org/software/
#
# This file will setup a homeassistant core following
# https://www.home-assistant.io/installation/raspberrypi-other#install-home-assistant-core
#
# This script is run as root, no need for sudo

CURRENT_USER=$( whoami )
echo "START install_hacore.sh as user: ${CURRENT_USER}"
echo "current directory is $( pwd )"
#install homeassistant dependencies
#sudo apt install -y python3 python3-dev python3-venv python3-pip bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff6 libturbojpeg0-dev tzdata ffmpeg liblapack3 liblapack-dev libatlas-base-dev
sudo apt install -y bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff6 libturbojpeg0-dev tzdata ffmpeg liblapack3 liblapack-dev libatlas-base-dev

#create homeassistant user
#sudo useradd -rm homeassistant
# also add the user to some groups for getting access to installed devices
# e.g. dialout is needed for access to my comBee III ZigBee stick
sudo useradd -rm homeassistant -G dialout,gpio,i2c

#create a directory for the installation of Home Assistant Core
mkdir /srv/homeassistant
chown homeassistant:homeassistant /srv/homeassistant

#change to homeassistant user and run some commands with that user
sudo -u homeassistant -H -s<<EOF

#go to homeassistant directory
cd /srv/homeassistant

#create and change to a virtual environment for Home Assistant Core
python3	-m venv .
source bin/activate

#we are now in the virtual environment
#install required Python packages
python3 -m pip install wheel
pip3 install homeassistant
EOF

#create service file
#sudo -i
cat <<EOF >/etc/systemd/system/homeassistant@homeassistant.service
[Unit]
Description=Home Assistant
After=network-online.target

[Service]
Type=simple
User=%i
WorkingDirectory=/home/%i/.homeassistant
ExecStart=/srv/homeassistant/bin/hass -c "/home/%i/.homeassistant"
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target

EOF

# create directory for running the homeassistant service
mkdir /home/homeassistant/.homeassistant
chown homeassistant:homeassistant /home/homeassistant/.homeassistant

# reload systemd to make the daemon aware of the new configuration
systemctl --system daemon-reload
# enable service
systemctl enable homeassistant@homeassistant

# # enable SSL/HTTPS
# # steps from https://community.home-assistant.io/t/certificate-authority-and-self-signed-certificate-for-ssl-tls/196970
# ETH_IP=
# cd /home/homeassistant/.homeassistant
# openssl req -sha256 -addext "subjectAltName = IP:X.X.X.X" -newkey rsa:4096 -nodes -keyout privkey.pem -x509 -days 730 -out fullchain.pem
# #set rights
# chown homeassistant:homeassistant fullchain.pem privkey.pem
# chmod 600 fullchain.pem privkey.pem
# # Update the http: entry in your configuration.yaml
# http:
#   ssl_certificate: /home/homeassistant/.homeassistant/fullchain.pem
#   ssl_key: /home/homeassistant/.homeassistant/privkey.pem

echo "END install_hacore.sh"
